### Create a sensor
POST http://localhost:3000/sensors
Content-Type: application/json

{
    "name": "Sensor 1",
    "type": "temp"
}

### Get All Sensors
GET http://localhost:3000/sensors


### Get All Sensors Of Type temp
GET http://localhost:3000/sensors/of?type=temp