### Create a Sensor
POST http://localhost:3000/sensors
Content-Type: application/json

{
    "name": "Sensor 1",
    "type": "temperature"
}

### Add new SensorData to a Sensor
POST http://localhost:3000/sensors/4a82c030-dfb3-4191-8a8e-936a705e8a89/data
Content-Type: application/json

{
    "value": 24.5
}

### Find all SensorData for a given Sensor
GET http://localhost:3000/sensors/4a82c030-dfb3-4191-8a8e-936a705e8a89/data

