### Create a Sensor
POST http://localhost:3000/sensors
Content-Type: application/json

{
    "name": "Sensor 1",
    "type": "temperature"
}

### Add new SensorData to a Sensor
POST http://localhost:3000/sensordata/6bc32e86-744b-4068-85c5-0382e559f80e
Content-Type: application/json

{
    "value": 24.5,
    "rawValue": 642.32
}

### Find all SensorData for a given Sensor
GET http://localhost:3000/sensordata/6bc32e86-744b-4068-85c5-0382e559f80e

