### Create a new User
PUT http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "User Three",
    "email": "three@some.user",
    "password": "aahg437879h(/HT/)($Ha"
}

### Signin a registered User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "three@some.user",
    "password": "aahg437879h(/HT/)($Ha"
}

### Sign out current user
POST http://localhost:3000/auth/signout

### Find a user with a given ID
GET http://localhost:3000/auth/4bff9d2e-021c-4de0-b532-71f0a96baf23


### Remove a user with a given ID
DELETE http://localhost:3000/auth/4bff9d2e-021c-4de0-b532-71f0a96baf23

### Update a user with a given ID
PATCH http://localhost:3000/auth/4bff9d2e-021c-4de0-b532-71f0a96baf23
Content-Type: application/json

{
    "password": "aahg437879h(/HT/)($Ha"
}

### Create a new User
PUT http://212.132.64.11/auth/signup
Content-Type: application/json

{
    "name": "Jan",
    "email": "j-suhrheinrich@gmx.de",
    "password": "jjW<3mzBS2$p6R&2CY$hE"
}
