### Create a station
POST http://localhost:3000/stations
Content-Type: application/json

{
    "name": "Station 1",
    "description": "My Station 1"
}

### Create a sensor
POST http://localhost:3000/sensors
Content-Type: application/json

{
    "name": "Sensor 3",
    "type": "temperature",
    "stationId": "722a7778-5d94-4302-b53b-c0d7c80f28a3"
}

### Get all sensors for a station
GET http://localhost:3000/stations/722a7778-5d94-4302-b53b-c0d7c80f28a3/sensors


### Station ID: 722a7778-5d94-4302-b53b-c0d7c80f28a3
